name: CI/CD Pipelines
on:
  push:
    branches:
      - feature/terraform-eks

permissions:
  id-token: write 
  contents: read
jobs:
  eks:
    runs-on: self-hosted
    strategy:
      max-parallel: 1
      matrix:
        include:
          - environment: dev
            region: us-east-1
          
         # - environment: test
         #   region: us-east-2
    env:
      TF_VAR_environment: ${{ matrix.environment }}
    defaults:
      run:
        working-directory: ${{ matrix.environment }}

    
    
    
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: aws-credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::083546510488:role/github-pipeline-eks
          aws-region: ${{ matrix.region }}  

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.0

      - name: terraform init
        run: terraform init
        
      
      - name: terraform plan
        run: terraform plan -out=tfplan

      - name: terraform  destroy
        run: terraform destroy -auto-approve
         

      
          